### PR TITLE
NATIVE-456: Upgrade sentry

### PR DESCRIPTION
**Pull request by klinzo**

### CODE REVIEW

**Comment by maxammann** [comment]
Did you test whether crashes get reported in release mode?

**Comment by maxammann** [comment]
I think we can merge this as long as Hermes is disabled. We can test this before the next release.

**Comment by Schedulaar** [comment]
What does Hermes have to do with it?

**Comment by maxammann** [comment]
Sentry does not yet work with Hermes, I think it is better to test after merging. We have to test sentry nonetheless before a proper release.

**Comment by klinzo** [comment]
I don't care whether to test it now or later. But @maxammann has a point that we have to do it anyway before a release.

**Comment by klinzo** [comment]
@maxammann ping

**Pull request merged**
