### PR TITLE
NATIVE-161: Rename extras to offers

### PR DESCRIPTION
**Pull request by SimonVortkamp**

### CODE REVIEW

**Comment by klinzo** [comment]
Are there no other locales containing the term `extras`?

**Comment by klinzo** [comment]
@maxammann are there other locales which should be changed? or is this good to go?

**Comment by klinzo** [comment]
Alright, not quite sure what to do here: With this changes we have the keys `offers` and `extras` mixed. Since the locales have already been updated by @maxammann prior to this task with the correct terms `Offer`, I'd reject this and rename all the keys in a different task (or don't rename at all).

**Comment by maxammann** [comment]
This is only a small part of the change. This is required right now such that the locales.json is compatible with the current source code. The other stuff will be done in: https://issues.integreat-app.de/browse/WEBAPP-497

**Pull request merged**
