### PR TITLE
NATIVE-609: Migrate to main

### PR DESCRIPTION
**Pull request by klinzo**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **NATIVE**.

### CODE REVIEW

**Review by maxammann — APPROVED** [review]
You will create the main branch when merging this, right?

**Comment by maxammann** [comment]
I think this should work fine :)

**Comment by Taggotty** [comment]
Still found one occurence of develop in Contributing.md . Please checkout if it should be replaced. 
I am a little bit worried that the bump-version will not work as expected whith a new branchref, but I guess we will see :)

**Review by Taggotty — APPROVED** [review]

**Comment by klinzo** [comment]
@Taggotty good catch, the line will be removed in https://github.com/Integreat/integreat-react-native-app/pull/299/files anyway, so I won't replace it here.

Not sure why it should not work as we get the new branch ref, so I hope you are wrong. If not though, I stand corrected :D

**Pull request merged**
