### PR TITLE
NATIVE-608: Fix build config gradle windows

### PR DESCRIPTION
**Pull request by klinzo**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **NATIVE**.

### CODE REVIEW

**Comment by klinzo** [comment]
@maxammann do you have any better ideas? The problem is that `yarn` and other node stuff is not available inside gradle on windows.

**Comment by maxammann** [comment]
The E2E is failing because of a missing BUILD_CONFIG_NAME:

```
08-19 14:13:11.004 E/ReactNativeJS( 1935): Error: No BUILD_CONFIG_NAME supplied!
08-19 14:13:11.007 E/ReactNativeJS( 1935): Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
08-19 14:13:11.010 E/AndroidRuntime( 1935): FATAL EXCEPTION: mqt_native_modules
08-19 14:13:11.010 E/AndroidRuntime( 1935): Process: tuerantuer.app.integreat, PID: 1935
08-19 14:13:11.010 E/AndroidRuntime( 1935): com.facebook.react.common.JavascriptException: Error: No BUILD_CONFIG_NAME supplied!, stack:
08-19 14:13:11.010 E/AndroidRuntime( 1935): _@895:329
08-19 14:13:11.010 E/AndroidRuntime( 1935): f@894:158
08-19 14:13:11.010 E/AndroidRuntime( 1935): <unknown>@1145:166
08-19 14:13:11.010 E/AndroidRuntime( 1935): v@2:1474
08-19 14:13:11.010 E/AndroidRuntime( 1935): <unknown>@1136:227
08-19 14:13:11.010 E/AndroidRuntime( 1935): v@2:1474
08-19 14:13:11.010 E/AndroidRuntime( 1935): <unknown>@1117:154
08-19 14:13:11.010 E/AndroidRuntime( 1935): v@2:1474
08-19 14:13:11.010 E/AndroidRuntime( 1935): <unknown>@399:243
08-19 14:13:11.010 E/AndroidRuntime( 1935): v@2:1474
08-19 14:13:11.010 E/AndroidRuntime( 1935): <unknown>@7:77
08-19 14:13:11.010 E/AndroidRuntime( 1935): v@2:1474
08-19 14:13:11.010 E/AndroidRuntime( 1935): <unknown>@6:30
08-19 14:13:11.010 E/AndroidRuntime( 1935): v@2:1474
08-19 14:13:11.010 E/AndroidRuntime( 1935): d@2:876
08-19 14:13:11.010 E/AndroidRuntime( 1935): global code@1742:4
08-19 14:13:11.010 E/AndroidRuntime( 1935): 
08-19 14:13:11.010 E/AndroidRuntime( 1935): 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
08-19 14:13:11.010 E/AndroidRuntime( 1935): 	at java.lang.reflect.Method.invoke(Native Method)
08-19 14:13:11.010 E/AndroidRuntime( 1935): 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
08-19 14:13:11.010 E/AndroidRuntime( 1935): 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
08-19 14:13:11.010 E/AndroidRuntime( 1935): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
08-19 14:13:11.010 E/AndroidRuntime( 1935): 	at android.os.Handler.handleCallback(Handler.java:873)
08-19 14:13:11.010 E/AndroidRuntime( 1935): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-19 14:13:11.010 E/AndroidRuntime( 1935): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
08-19 14:13:11.010 E/AndroidRuntime( 1935): 	at android.os.Looper.loop(Looper.java:193)
08-19 14:13:11.010 E/AndroidRuntime( 1935): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
08-19 14:13:11.010 E/AndroidRuntime( 1935): 	at java.lang.Thread.run(Thread.java:764)
08-19 14:13:11.045 I/Process ( 1935): Sending signal. PID: 1935 SIG: 9
08-19 14:13:11.078 I/ActivityManager( 1221): Process tuerantuer.app.integreat (pid 1935) has died: vis  +99TOP 
```

**Comment by maxammann** [comment]
This is already fixed in NATIVE-541

**Review by Taggotty — COMMENTED** [review]
For now I think the solution is feasable, but if any more inconveniences occur to complicate this part here I'd say it would be better to look for another solution

**Comment by klinzo** [comment]
As discussed: Will be closed because it is a bad solution. @maxammann will do a quick online research if there are better solutions.

**Comment by maxammann** [comment]
I think we need to create a .bat script for this. This is callable via gradle

**Pull request closed without merging**
