### PR TITLE
NATIVE-558: Add appName to translate functions

### PR DESCRIPTION
**Pull request by maxammann**
This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **NATIVE**.

### CODE REVIEW

**Comment by maxammann** [comment]
relevant locales:

```
app.pageTitles.mainDisclaimer,Impressum und Kontakt - {{appName}},Imprint and contacts - {{appName}}
app.metaDescription,"{{appName}} ist Ihr digitaler Guide für Deutschland. Finden Sie lokale Informationen, Veranstaltungen und Beratung. Immer aktuell und in Ihrer Sprache.","{{appName}} is your digital guide to life in Germany. Discover local information, events and advice. Always up to date and available in your own language."
feedback.thanksMessage,"Vielen Dank für Ihr Feedback. Damit helfen Sie uns, unsere Inhalte und die {{appName}}-App zu verbessern. Wir würden uns über weiteres Feedback freuen.",Thank you for your feedback. This will help us to improve our content and the {{appName}} app. We would be happy to receive further feedback.
intro.integreat,{{appName}},{{appName}}
intro.integreatDescription,{{appName}} ist Ihr digitaler Guide für Deutschland,{{appName}} is your digital guide to life in Germany
intro.inquiryIntro,"Durch Klicken auf ""{{accept}}"" erlaube ich der {{appName}}-App, ...","By clicking on ""{{accept}}"" I accept the {{appName}} app, ..."
intro.sentryCondition,... mit dem automatischen Senden von Absturzberichten {{appName}} zu verbessern,...improving {{appName}} by automatically sending crash reports
settings.sentryDescription,Durch das automatische Senden von Absturzberichten die {{appName}}-App verbessern,Improve the {{appName}} app by automatically sending crash reports
settings.about,Über {{appName}},About {{appName}}
```

**Comment by maxammann** [comment]
@Taggotty did not see that you are already doing the webapp task. Above are the relevant locales

**Comment by klinzo** [comment]
Don't we have to pull the locales first?

**Comment by maxammann** [comment]
@klinzo no, this change does not do any harm without the locales

**Comment by klinzo** [comment]
What are we waiting for though? Translation of malte locales?

**Comment by maxammann** [comment]
Nothing we can merge this right now. It is just not used until the translations of malte are finished

**Pull request merged**
